AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Persists data in ElastiCache
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  RedisURL:
    Type: String
    Description: Redis URL

Resources:
  LoaderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loader/
      Handler: app.apiHandler
      Runtime: nodejs18.x
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save
            Method: get
      VpcConfig:
        SecurityGroupIds:
        - !ImportValue 'SecurityGroupId'
        SubnetIds:
        - !ImportValue 'CardAuthPrivateSubnet1'
      Environment:
        Variables:
          REDIS_URL: !Ref RedisURL
      Policies:
       - CloudWatchPutMetricPolicy: {}
#      - AdministratorAccess

    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  QueueFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: loader/
      Handler: app.queueHandler
      Runtime: nodejs18.x
      Timeout: 30
      Tracing: Active
      AutoPublishAlias: live
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Architectures:
        - x86_64
      Events:
        QueueEvent:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Queue: !ImportValue 'QueueARN'
      Policies:
      - AmazonSQSFullAccess
      - AmazonEC2FullAccess
      VpcConfig:
        SecurityGroupIds:
        - !ImportValue 'SecurityGroupId'
        SubnetIds:
        - !ImportValue 'CardAuthPrivateSubnet1'
      Environment:
        Variables:
          REDIS_URL: !Ref RedisURL


    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LoaderApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send/"
